project:
  type: website

lang: es

website:
  title: "Santiago Sotelo"
  google-analytics: "G-34G2Z2VLGJ"
  favicon: peru.png
  navbar:
    search: false

format:
  html:
    theme: ember.scss #base on litera
    css: styles.css



